enable-magisk-update = true

GLOBAL SELECTIONS


parallel-jobs = 1
cli-source = "revanced/revanced-cli"         
cli-version = "latest" 
rv-brand = "Prathxm ReVanced"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
patches-version = "dev"
arch = "arm64-v8a"


[YouTube-OG]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
app-name = "YouTube"
included-patches = "'Theme'"
patcher-args = "-e 'Settings for YouTube' -OrvxSettingsLabel='Prathxm Rvx' -e 'GmsCore support' -OpackageNameYouTube=prathxm.youtube"



[YouTube-OG-MaterialYou]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
app-name = "YouTube"
included-patches = "'MaterialYou' 'Theme'"
patcher-args = "-e 'Settings for YouTube' -OrvxSettingsLabel='Prathxm Rvx' -e 'GmsCore support' -OpackageNameYouTube=prathxm.youtube"


[YouTube-Custom]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
app-name = "YouTube"
included-patches = "'Theme'"
patcher-args = "-e 'Settings for YouTube' -OrvxSettingsLabel='Prathxm Rvx' -e 'GmsCore support' -OpackageNameYouTube=prathxm.youtube -e 'Custom branding icon for YouTube' -OappIcon=revancify_red -OchangeSplashIcon=true"



[YouTube-Custom-MaterialYou]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
app-name = "YouTube"
included-patches = "'MaterialYou' 'Theme'"
patcher-args = "-e 'Settings for YouTube' -OrvxSettingsLabel='Prathxm Rvx' -e 'GmsCore support' -OpackageNameYouTube=prathxm.youtube -e 'Custom branding icon for YouTube' -OappIcon=revancify_red -OchangeSplashIcon=true"



# YOUTUBE MUSIC

[Music-OG]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
app-name = "YouTube-Music"
build-mode = "both"
patcher-args = "-e 'Settings for YouTube Music' -OrvxSettingsLabel='Prathxm Rvx' -e 'GmsCore support' -OpackageNameYouTubeMusic=prathxm.youtube.music"


[Music-Custom]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
app-name = "YouTube-Music"
build-mode = "both"
patcher-args = "-e 'Settings for YouTube Music' -OrvxSettingsLabel='Prathxm Rvx' -e 'GmsCore support' -OpackageNameYouTubeMusic=prathxm.youtube.music -e 'Custom branding icon for YouTube Music' -OappIcon=revancify_red -OchangeSplashIcon=true"







